pipeline {
    agent any

    environment {
        // Define default project variables
        BUILD_NAME = 'CRM Automation Pipeline'
        BROWSER = 'Chrome'
        ENVIRONMENT = 'QA'
        REPORTS_DIR = 'reports'
    }

    stages {
        stage('Build & Execute Tests') {
            steps {
                echo '====== Executing Tests ======'
                
                // For Java / Maven projects:
                bat 'mvn clean test'
                
                // For Node.js / Newman API test projects (uncomment if using npm):
                // bat 'npm test'
            }
        }
    }

    post {
        always {
            echo "====== Publishing Reports & Archiving Artifacts ======"

            // 1. Publish Extent / HTML Reports & Newman HTML extra reports
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: "${env.REPORTS_DIR}",
                reportFiles: "*.html",
                reportName: "Extent & API Reports"
            ])

            // 1b. Publish per-test HTML reports generated by the pipeline
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: "${env.REPORTS_DIR}/per_test",
                reportFiles: "**/*.html",
                reportName: "Per-test Reports"
            ])

            // Debug: list per-test reports so console shows whether files exist
            bat '''
                echo Listing per-test reports directory
                if exist "reports\\per_test" (
                    dir "reports\\per_test" /B
                ) else (
                    echo reports\\per_test not found
                )
            '''

            // 2. Publish JUnit XML Results (Includes Surefire and Newman XML reports)
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml, reports/newman-report-*.xml'

            // 3. Archive Test Artifacts (Reports, Logs, Screenshots, XMLs)
            archiveArtifacts artifacts: 'reports/**/*.html, reports/**/*.xml, logs/**/*.log, screenshots/**/*.png', 
                             allowEmptyArchive: true, 
                             onlyIfSuccessful: false

            // 4. Send Webhook Data to n8n via Windows Batch Curl
            script {
                def buildStatus = currentBuild.result ?: 'SUCCESS'
                
                // Set status in env so single-quoted batch script reads it cleanly
                env.JOB_BUILD_STATUS = buildStatus
                
                bat '''
                    curl -X POST ^
                    -H "Content-Type: application/json" ^
                    -H "Bypass-Tunnel-Remainder: true" ^
                    -d "{\\"build_name\\":\\"%BUILD_NAME%\\", \\"status\\":\\"%JOB_BUILD_STATUS%\\", \\"browser\\":\\"%BROWSER%\\", \\"environment\\":\\"%ENVIRONMENT%\\", \\"jenkins_url\\":\\"%BUILD_URL%\\"}" ^
                    https://tender-zebras-lose.loca.lt/webhook/jenkins-report
                '''
            }
        }

        cleanup {
            echo "====== Cleaning Workspace ======"
            deleteDir()
        }
    }
}