post {
        always {
            echo "====== Publishing Reports & Archiving Artifacts ======"

            // 1. Publish Extent / HTML Reports & Newman HTML extra reports
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: "${env.REPORTS_DIR}",
                reportFiles: "*.html",
                reportName: "Extent & API Reports"
            ])

            // 1b. Publish per-test HTML reports generated by the pipeline
            publishHTML([
                allowMissing: true,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: "${env.REPORTS_DIR}/per_test",
                reportFiles: "**/*.html",
                reportName: "Per-test Reports"
            ])

            // Debug: list per-test reports so console shows whether files exist
            bat '''
                echo Listing per-test reports directory
                if exist "reports\\per_test" (
                    dir "reports\\per_test" /B
                ) else (
                    echo reports\\per_test not found
                )
            '''

            // 2. Publish JUnit XML Results (Includes Surefire and Newman XML reports)
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml, reports/newman-report-*.xml'

            // 3. Archive Test Artifacts (Reports, Logs, Screenshots, XMLs)
            archiveArtifacts artifacts: 'reports/**/*.html, reports/**/*.xml, logs/**/*.log, screenshots/**/*.png', 
                             allowEmptyArchive: true, 
                             onlyIfSuccessful: false

            // 4. Send Webhook Data to n8n via Windows Batch Curl (Using Single-Quoted Command Block)
            script {
                def buildStatus = currentBuild.result ?: 'SUCCESS'
                
                bat '''
                    curl -X POST ^
                    -H "Content-Type: application/json" ^
                    -d "{\\"build_name\\":\\"%BUILD_NAME%\\", \\"status\\":\\"%BUILD_STATUS%\\", \\"browser\\":\\"%BROWSER%\\", \\"environment\\":\\"%ENVIRONMENT%\\", \\"jenkins_url\\":\\"%BUILD_URL%\\"}" ^
                    https://wicked-suits-open.loca.lt/webhook/jenkins-report
                '''
            }
        }

        cleanup {
            echo "====== Cleaning Workspace ======"
            deleteDir()
        }
    }