# ============================================
# CRM Application Configuration
# ============================================

# Application URL
app.url=https://crm.osllc.us/admin/auth/login

# Browser Configuration
browser=chrome
headless=false
implicit.wait=1
explicit.wait=4
page.load.timeout=30

# Chrome Options
chrome.args=--start-maximized,--disable-blink-features=AutomationControlled,--disable-notifications,--disable-popup-blocking,--password-store=basic
#chrome.args=--start-maximized,--disable-blink-features=AutomationControlled,--headless

# Firefox Options
firefox.args=--start-maximized

# User Credentials
username=demo
password=5555

# Screenshot
screenshot.path=./screenshots/
screenshot.on.failure=true

# Reports
reports.path=./reports/
test.data.path=./testdata/

# Logger
log.level=INFO
log.file.path=./logs/

# Retry Configuration
# Set to 0 to disable automatic retries so each test runs only once
retry.count=0

# Email Notification
send.email.report=false
email.recipients=test@example.com
